### ISSUE TITLE
App should show for each character how many points is needed to get to the next LL

### ISSUE THREAD

**Issue by nessus42** [tomcorke/destiny-power-bars#1]
You've made an incredible tool! Thanks so much!

One feature that I miss from Destiny 2 Power Calculator is a display for each character on how many gear LL points are required to get to the next total LL. If Power Bars had this feature, it would be utterly perfect!

P.S. I know that you can mouse over the "?" for this info, but that only works if you can raise your LL via world drops. This number should always be shown, and it should be on the main screen. Thanks again for your consideration and hard work!

**Comment by tomcorke** [comment]
Closed as feature was added :)
