### ISSUE TITLE
App should look for armor on other characters

### ISSUE THREAD

**Issue by nessus42** [tomcorke/destiny-power-bars#2]
When calculating the current maximum LL for my Warlock, for instance, Power Bars seems to correctly look on both my Warlock and my Vault for Warlock armor. It doesn't look, however, for Warlock armor on my Titan or Hunter.

Maybe most people don't end up in this situation, but DIM will do it for me automatically, if my Vault space is running low, as it will just find empty slots anywhere to move gear into.

**Comment by tomcorke** [comment]
This has now been fixed, sorry it took so long :)
