### ISSUE TITLE
App Can't Fetch Character Data

### ISSUE THREAD

**Issue by gkallenberg** [tomcorke/destiny-power-bars#7]
Having issues with the app and access to character data in Win10 Chrome. Seems to be fine in Firefox 81.0 (64-bit). The app's spinner at the bottom cycles between fetching data, and the no data message repeatedly.

Here is the Chrome version:
  Win10 Chrome Version 86.0.4240.198 (Official Build) (64-bit)

Let me know if you need more info.

**Comment by gkallenberg** [comment]
Error in Chrome console:

```
Error fetching character data: TypeError: Cannot read property 'displayProperties' of undefined
    at $r (utils.ts:310)
    at utils.ts:505
    at Array.map (<anonymous>)
    at utils.ts:504
    at s (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
(anonymous) @ App.tsx:147
s @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:29
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ App.tsx:135
g @ debounce.js:95
b @ debounce.js:105
_ @ debounce.js:172
(anonymous) @ App.tsx:320
Al @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Tl @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
D @ scheduler.production.min.js:16
k.port1.onmessage @ scheduler.production.min.js:12
```

**Comment by tomcorke** [comment]
Hi @gkallenberg - sorry, I didn't see this at the time you posted it. Has it fixed itself since?

The nature of the error implies the definitions for an item were out of sync with something else the API was returning. I'd expect that'll fix itself as the app gets the latest version of those definitions. If it's still causing issues, please let me know so I can look into more specifics!

**Comment by gkallenberg** [comment]
Sorry, I didn't see your earlier comment. The error did stop happening on Chrome so I think you're good to go. Thanks for the reply, and your attention on this.
