### ISSUE TITLE
Should not show equipment in vault by default

### ISSUE THREAD

**Issue by julesrx** [tomcorke/destiny-power-bars#8]
I don't think items that are in the vault should be displayed by default in the power calculations.
If it isn't on the character, it will not count for the power level (i think).

The icon is present, but it could be misleading for new player who don"t know this mechanic
![image](https://user-images.githubusercontent.com/25800503/100389994-45592b80-302f-11eb-8a4a-3064708629d9.png)

**Comment by tomcorke** [comment]
Hi @julesrx , it has been tested and shown that items in the vault _do_ count for your power. You can test this by moving powerful items between your vault and inventory, and checking the power level of the items you can pull from your season pass.

Whether items are equipped, in your character inventory, in your vault, equipped on another character (e.g. weapons) or even in your postmaster, they all still count!
